name: push to bitbucket
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        git remote add staging ssh://ubuntu@ec2-18-191-182-101.us-east-2.compute.amazonaws.com/home/codimg-frontend
        git config --global user.email "ebwinters@comcast.net"
        git config --global user.name "ebwinters"
        git checkout master
        git push -f staging master
